---
- name: Install the latest version of cntlm
  hosts: localhost
  tasks:
    - name: Install the latest version of cntlm
      ansible.builtin.yum:
        name: cntlm
        state: latest

    - name: Add cntlm configuration
      ansible.builtin.template:
        src: ./templates/cntlm.conf
        dest: /etc/cntlm.conf
        owner: root
        group: root
        mode: "0644"

    - name: Set general system proxy
      ansible.builtin.template:
        src: ./templates/cntlm.sh
        dest: /etc/profile.d/cntlm.sh
        owner: root
        group: root
        mode: "0644"

    - name: Stop service cntlm
      ansible.builtin.service:
        name: cntlm
        state: stopped

    - name: Disable service cntlm, and not touch the state
      ansible.builtin.service:
        name: cntlm
        enabled: false
