- hosts:        localhost
  tasks:
    - name:     Add gpgkey
      rpm_key:
        state:  present
        key:    https://packagecloud.io/AtomEditor/atom/gpgkey

    - name:     Add yum repository
      template:
        src:    ./templates/atom.repo
        dest:   /etc/yum.repos.d/atom.repo
        owner:  root
        group:  root
        mode:   '0644'

    - name:     Install the latest version of Atom
      yum:
        name:   atom
        state:  latest

    - name:     Install atom plugins
      command:  /usr/bin/apm install language-docker pretty-json language-vue
