- name:            Atom
  import_playbook: ./playbooks/atom/base.yml
- name:            Bash
  import_playbook: ./playbooks/bash/base.yml
- name:            Cntlm
  import_playbook: ./playbooks/cntlm/base.yml
- name:            Curl
  import_playbook: ./playbooks/curl/base.yml
- name:            docker
  import_playbook: ./playbooks/docker/base.yml
- name:            dos2unix
  import_playbook: ./playbooks/dos2unix/base.yml
- name:            firefox
  import_playbook: ./playbooks/firefox/base.yml
- name:            git
  import_playbook: ./playbooks/git/base.yml
- name:            jq
  import_playbook: ./playbooks/jq/base.yml
- name:            lynx
  import_playbook: ./playbooks/lynx/base.yml
- name:            vim
  import_playbook: ./playbooks/vim/base.yml
- name:            wget
  import_playbook: ./playbooks/wget/base.yml
