- hosts:        localhost
  tasks:
    - name:     Install the latest version of git
      yum:
        name:   git
        state:  latest

    - name:     Configure git
      template:
        src:    ./templates/.gitconfig
        dest:   /home/vagrant/.gitconfig
        owner:  vagrant
        group:  vagrant
        mode:   '0644'
