- hosts:            localhost
  tasks:
  - name:           Add gpgkey
    rpm_key:
      state:        present
      key:          https://download.docker.com/linux/centos/gpg

  - name:           Add repository
    yum_repository:
      name:         docker-ce-stable
      description:  Docker CE Stable
      baseurl:      https://download.docker.com/linux/centos/7/$basearch/stable

  - name:           Install the latest version of docker-ce
    yum:
      name:         docker-ce
      state:        latest

  - name:           Download docker-compose
    get_url:
      url:          https://github.com/docker/compose/releases/download/1.24.1/docker-compose-Linux-x86-64
      dest:         /usr/local/bin/docker-compose

  - name:           Start service docker, if not started
    service:
      name:         docker
      state:        started

  - name:           Enable service docker, and not touch the state
    service:
      name:         docker
      enabled:      yes

  - name:           Adding vagrant to docker group
    user:
      name:         vagrant
      groups:       docker
      append:       yes
