---
- name: Install the latest version of docker-ce
  hosts: localhost
  tasks:
    - name: Add gpgkey
      ansible.builtin.rpm_key:
        state: present
        key: https://download.docker.com/linux/centos/gpg

    - name: Add repository
      ansible.builtin.yum_repository:
        name: docker-ce-stable
        description: Docker CE Stable
        baseurl: https://download.docker.com/linux/centos/7/$basearch/stable

    - name: Install the latest version of docker-ce
      ansible.builtin.yum:
        name: docker-ce
        state: latest

    - name: Download docker-compose
      ansible.builtin.get_url:
        url: https://github.com/docker/compose/releases/download/1.24.1/docker-compose-Linux-x86-64
        dest: /usr/local/bin/docker-compose
        mode: "755"

    - name: Start service docker, if not started
      ansible.builtin.service:
        name: docker
        state: started

    - name: Enable service docker, and not touch the state
      ansible.builtin.service:
        name: docker
        enabled: true

    - name: Adding vagrant to docker group
      ansible.builtin.user:
        name: vagrant
        groups: docker
        append: true
