- hosts:        localhost
  tasks:
    - name:     Install the latest version of git
      yum:
        name:   git
        state:  latest

    - name:     Configure git
      template:
        src:    ./templates/.gitconfig
        dest:   /home/vagrant/.gitconfig
        owner:  vagrant
        group:  vagrant
        mode:   '0644'

    - name: Create public key file
      file:
        path: /home/vagrant/.ssh/id_rsa.pub
        owner: vagrant
        group: vagrant
        mode: '0664'
        state: touch

    - name: Create private key file
      file:
        path: /home/vagrant/.ssh/id_rsa
        owner: vagrant
        group: vagrant
        mode: '0400'
        state: touch

    - name: Set public key
      copy: content="{{ git['public'] }}" dest=/home/vagrant/.ssh/id_rsa.pub

    - name: Set private key
      copy: content="{{ git['private'] }}" dest=/home/vagrant/.ssh/id_rsa
