---
- name: Install the latest version of vim
  hosts: localhost
  tasks:
    - name: Install the latest version of vim
      ansible.builtin.yum:
        name: vim
        state: latest

    - name: Configure vim
      ansible.builtin.template:
        src: ./templates/.vimrc
        dest: /home/vagrant/.vimrc
        owner: vagrant
        group: vagrant
        mode: "0644"
