---
- name: Install the latest version of bash
  hosts: localhost
  tasks:
    - name: Install the latest version of bash
      ansible.builtin.yum:
        name:
          - bash
          - bash-completion
        state: latest

    - name: Configure bash rc
      ansible.builtin.template:
        src: ./templates/.bashrc
        dest: /home/vagrant/.bashrc
        owner: vagrant
        group: vagrant
        mode: "0644"

    - name: Configure bash profile
      ansible.builtin.template:
        src: ./templates/.bash_profile
        dest: /home/vagrant/.bash_profile
        owner: vagrant
        group: vagrant
        mode: "0644"
